// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7z0xC7AljkeKFDtLc0XyKNYXHx31_cdI',
    appId: '1:596306462449:web:689c5a8766927d4ceacb50',
    messagingSenderId: '596306462449',
    projectId: 'communityapp-89418',
    authDomain: 'communityapp-89418.firebaseapp.com',
    storageBucket: 'communityapp-89418.appspot.com',
    measurementId: 'G-BDFJCLVHR7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtqwXH-X8f3yU7XMTWqV7AbfBcqZvEpW0',
    appId: '1:596306462449:android:86eeb1897f747b4deacb50',
    messagingSenderId: '596306462449',
    projectId: 'communityapp-89418',
    storageBucket: 'communityapp-89418.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjIyzwoJi3lAGohuHlEWNDwAOTB_1JXIk',
    appId: '1:596306462449:ios:0ac04dc4ca18c853eacb50',
    messagingSenderId: '596306462449',
    projectId: 'communityapp-89418',
    storageBucket: 'communityapp-89418.appspot.com',
    iosBundleId: 'com.example.communitySocialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjIyzwoJi3lAGohuHlEWNDwAOTB_1JXIk',
    appId: '1:596306462449:ios:8e9d495ce070b0c0eacb50',
    messagingSenderId: '596306462449',
    projectId: 'communityapp-89418',
    storageBucket: 'communityapp-89418.appspot.com',
    iosBundleId: 'com.example.communitySocialApp.RunnerTests',
  );
}
